"""extend_tasks_schema_with_description_status_and_labels

Revision ID: 13ddfb722106
Revises: 546d8cc0a02e
Create Date: 2026-07-09 23:59:20.068859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13ddfb722106'
down_revision: Union[str, Sequence[str], None] = '546d8cc0a02e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('tasks', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('tasks', sa.Column('labels', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'labels')
    op.drop_column('tasks', 'status')
    op.drop_column('tasks', 'description')
    # ### end Alembic commands ###
