"""add_project_is_template_flag

Revision ID: 2430efc7dbd0
Revises: 48d09df4d221
Create Date: 2026-07-11 21:02:22.330449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2430efc7dbd0'
down_revision: Union[str, Sequence[str], None] = '48d09df4d221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_template', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_template')
    # ### end Alembic commands ###
