"""add_deleted_fields_to_project_and_task

Revision ID: 36ffc7e29b11
Revises: 872312907774
Create Date: 2026-07-12 01:23:40.718223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36ffc7e29b11'
down_revision: Union[str, Sequence[str], None] = '872312907774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('projects', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tasks', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'deleted_at')
    op.drop_column('tasks', 'is_deleted')
    op.drop_column('projects', 'deleted_at')
    op.drop_column('projects', 'is_deleted')
    # ### end Alembic commands ###
