"""add_task_production_fields

Revision ID: 4280cd5642c6
Revises: 1e5cca6c7526
Create Date: 2026-07-11 15:47:14.787645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4280cd5642c6'
down_revision: Union[str, Sequence[str], None] = '1e5cca6c7526'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('story_points', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('estimated_time', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('tasks', sa.Column('attachments', sa.JSON(), nullable=True, server_default=sa.text("'[]'::jsonb")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'attachments')
    op.drop_column('tasks', 'is_archived')
    op.drop_column('tasks', 'estimated_time')
    op.drop_column('tasks', 'story_points')
    # ### end Alembic commands ###
