"""add_workspace_member_capacity

Revision ID: 48d09df4d221
Revises: 952d95ef7efb
Create Date: 2026-07-11 20:24:43.727660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48d09df4d221'
down_revision: Union[str, Sequence[str], None] = '952d95ef7efb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace_members', sa.Column('weekly_capacity_hours', sa.Integer(), nullable=False, server_default='40'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspace_members', 'weekly_capacity_hours')
    # ### end Alembic commands ###
