"""add_missing_model_columns

Revision ID: 4b79e4a71cc7
Revises: 264877750575
Create Date: 2026-07-17 17:34:44.132661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b79e4a71cc7'
down_revision: Union[str, Sequence[str], None] = '264877750575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspace_integrations')
    op.alter_column('activities', 'details',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index(op.f('ix_activities_category'), 'activities', ['category'], unique=False)
    op.create_index(op.f('ix_activities_created_at'), 'activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_activities_event_type'), 'activities', ['event_type'], unique=False)
    op.create_index(op.f('ix_activities_target_type'), 'activities', ['target_type'], unique=False)
    op.add_column('comment_replies', sa.Column('content_markdown', sa.Text(), nullable=True))
    op.add_column('comment_replies', sa.Column('mentions', sa.JSON(), nullable=True))
    op.add_column('comment_replies', sa.Column('reactions', sa.JSON(), nullable=True))
    op.add_column('comment_replies', sa.Column('attachments', sa.JSON(), nullable=True))
    op.add_column('comment_replies', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('comments', sa.Column('content_markdown', sa.Text(), nullable=True))
    op.add_column('comments', sa.Column('mentions', sa.JSON(), nullable=True))
    op.add_column('comments', sa.Column('reactions', sa.JSON(), nullable=True))
    op.add_column('comments', sa.Column('attachments', sa.JSON(), nullable=True))
    op.add_column('comments', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sprints', sa.Column('description', sa.String(length=2000), nullable=True))
    op.add_column('sprints', sa.Column('is_archived', sa.Boolean(), nullable=True))
    op.add_column('sprints', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('start_date', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'start_date')
    op.drop_column('sprints', 'archived_at')
    op.drop_column('sprints', 'is_archived')
    op.drop_column('sprints', 'description')
    op.drop_column('comments', 'updated_at')
    op.drop_column('comments', 'attachments')
    op.drop_column('comments', 'reactions')
    op.drop_column('comments', 'mentions')
    op.drop_column('comments', 'content_markdown')
    op.drop_column('comment_replies', 'updated_at')
    op.drop_column('comment_replies', 'attachments')
    op.drop_column('comment_replies', 'reactions')
    op.drop_column('comment_replies', 'mentions')
    op.drop_column('comment_replies', 'content_markdown')
    op.drop_index(op.f('ix_activities_target_type'), table_name='activities')
    op.drop_index(op.f('ix_activities_event_type'), table_name='activities')
    op.drop_index(op.f('ix_activities_created_at'), table_name='activities')
    op.drop_index(op.f('ix_activities_category'), table_name='activities')
    op.alter_column('activities', 'details',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)
    op.create_table('workspace_integrations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('credentials', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('workspace_integrations_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workspace_integrations_pkey'))
    )
    # ### end Alembic commands ###
