"""extend projects schema with slug cover priority favorite and pinned

Revision ID: 546d8cc0a02e
Revises: b5f8def92a4d
Create Date: 2026-07-09 23:00:23.143570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '546d8cc0a02e'
down_revision: Union[str, Sequence[str], None] = 'b5f8def92a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('slug', sa.String(length=255), nullable=False))
    op.add_column('projects', sa.Column('cover_image', sa.String(length=1024), nullable=True))
    op.add_column('projects', sa.Column('priority', sa.String(length=50), nullable=False))
    op.add_column('projects', sa.Column('is_favorite', sa.Boolean(), nullable=False))
    op.add_column('projects', sa.Column('is_pinned', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_column('projects', 'is_pinned')
    op.drop_column('projects', 'is_favorite')
    op.drop_column('projects', 'priority')
    op.drop_column('projects', 'cover_image')
    op.drop_column('projects', 'slug')
    # ### end Alembic commands ###
