"""extend_api_keys_and_add_usage_history

Revision ID: 5a2b03834f10
Revises: 696facd0040f
Create Date: 2026-07-12 01:41:06.142483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a2b03834f10'
down_revision: Union[str, Sequence[str], None] = '696facd0040f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_key_usage_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('api_key_id', sa.Uuid(), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('api_keys', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('api_keys', sa.Column('scopes', sa.JSON(), nullable=True))
    op.add_column('api_keys', sa.Column('last_used_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'last_used_at')
    op.drop_column('api_keys', 'scopes')
    op.drop_column('api_keys', 'expires_at')
    op.drop_table('api_key_usage_history')
    # ### end Alembic commands ###
