"""add_workspace_accent_color

Revision ID: 5f09f227f8ec
Revises: c8f307adad0c
Create Date: 2026-07-11 21:20:47.632161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f09f227f8ec'
down_revision: Union[str, Sequence[str], None] = 'c8f307adad0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('accent_color', sa.String(length=50), nullable=False, server_default='#5BB98C'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'accent_color')
    # ### end Alembic commands ###
