"""create_comment_replies_and_project_discussions

Revision ID: 6363fcd4dae5
Revises: 77180c9229f1
Create Date: 2026-07-10 15:03:49.204756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6363fcd4dae5'
down_revision: Union[str, Sequence[str], None] = '77180c9229f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_replies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('comment_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('comments', sa.Column('project_id', sa.Uuid(), nullable=True))
    op.alter_column('comments', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'comments', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.alter_column('comments', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('comments', 'project_id')
    op.drop_table('comment_replies')
    # ### end Alembic commands ###
