"""add_task_dependencies_and_subtasks

Revision ID: 7e2046c1b664
Revises: dc7c1c1ff99c
Create Date: 2026-07-11 16:06:04.649018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e2046c1b664'
down_revision: Union[str, Sequence[str], None] = 'dc7c1c1ff99c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_dependencies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('depends_on_id', sa.Uuid(), nullable=False),
    sa.Column('dependency_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tasks', sa.Column('parent_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'tasks', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'parent_id')
    op.drop_table('task_dependencies')
    # ### end Alembic commands ###
