"""add_fields_to_saved_filters

Revision ID: a03f698ca216
Revises: 36ffc7e29b11
Create Date: 2026-07-12 01:27:29.356904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a03f698ca216'
down_revision: Union[str, Sequence[str], None] = '36ffc7e29b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_filters', sa.Column('layout', sa.String(length=50), nullable=True))
    op.add_column('saved_filters', sa.Column('is_favorite', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('saved_filters', sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_filters', 'last_used_at')
    op.drop_column('saved_filters', 'is_favorite')
    op.drop_column('saved_filters', 'layout')
    # ### end Alembic commands ###
