"""add color and icon to projects

Revision ID: a783da6240a9
Revises: 25b26351cab2
Create Date: 2026-07-08 21:52:50.559761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a783da6240a9'
down_revision: Union[str, Sequence[str], None] = '25b26351cab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('icon', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('color', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'color')
    op.drop_column('projects', 'icon')
    # ### end Alembic commands ###
