"""add archive visibility and workspace id columns to projects

Revision ID: b5f8def92a4d
Revises: e371d238e5e4
Create Date: 2026-07-08 22:13:28.404176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5f8def92a4d'
down_revision: Union[str, Sequence[str], None] = 'e371d238e5e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('workspace_id', sa.Uuid(), nullable=True))
    op.add_column('projects', sa.Column('visibility', sa.String(length=50), nullable=False))
    op.add_column('projects', sa.Column('is_archived', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_archived')
    op.drop_column('projects', 'visibility')
    op.drop_column('projects', 'workspace_id')
    # ### end Alembic commands ###
