"""add notification toggles to workspaces

Revision ID: c8abaea24146
Revises: 3d4d73897134
Create Date: 2026-07-10 21:22:36.302946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8abaea24146'
down_revision: Union[str, Sequence[str], None] = '3d4d73897134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('enable_email_notifications', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('workspaces', sa.Column('enable_desktop_notifications', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'enable_desktop_notifications')
    op.drop_column('workspaces', 'enable_email_notifications')
    # ### end Alembic commands ###
