"""add_project_kanban_columns

Revision ID: dc7c1c1ff99c
Revises: 4280cd5642c6
Create Date: 2026-07-11 15:52:13.812949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dc7c1c1ff99c'
down_revision: Union[str, Sequence[str], None] = '4280cd5642c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('kanban_columns', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'kanban_columns')
    # ### end Alembic commands ###
