"""create sprints table and link tasks

Revision ID: f7402715ae96
Revises: c8abaea24146
Create Date: 2026-07-10 21:35:32.319767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7402715ae96'
down_revision: Union[str, Sequence[str], None] = 'c8abaea24146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS sprints CASCADE")
    op.create_table(
        'sprints',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('project_id', sa.Uuid(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('goal', sa.String(length=1000), nullable=True),
        sa.Column('duration_weeks', sa.Integer(), nullable=False),
        sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tasks', sa.Column('sprint_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'sprints', ['sprint_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'sprint_id')
    op.add_column('sprints', sa.Column('completed_tasks', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sprints', sa.Column('total_tasks', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sprints', sa.Column('velocity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'sprints', type_='foreignkey')
    op.alter_column('sprints', 'end_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('sprints', 'start_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('sprints', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('sprints', 'updated_at')
    op.drop_column('sprints', 'status')
    op.drop_column('sprints', 'duration_weeks')
    op.drop_column('sprints', 'goal')
    op.drop_column('sprints', 'project_id')
    # ### end Alembic commands ###
